# Generated by Django 4.2.7 on 2025-07-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_rename_candle_count_strategycondition_left_candle_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategycondition',
            name='sl_tp_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategycondition',
            name='value_type',
            field=models.CharField(blank=True, choices=[('percent', 'Percentage'), ('points', 'Points')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='strategycondition',
            name='comparison_type',
            field=models.CharField(choices=[('spot', 'Spot'), ('ohlc_vs_ltp', 'OHLC vs LTP'), ('ohlc_vs_ohlc', 'OHLC Compare'), ('ohlc_vs_indicator', 'OHLC With Indicator'), ('indicator_vs_indicator', 'Indicator vs Indicator'), ('indicator_vs_value', 'Single Indicator')], max_length=32),
        ),
        migrations.AlterField(
            model_name='strategycondition',
            name='type',
            field=models.CharField(choices=[('pre_buy', 'Pre Buy'), ('buy', 'Buy'), ('pre_sell', 'Pre Sell'), ('sell', 'Sell'), ('stop_loss', 'Stop Loss'), ('target', 'Target')], max_length=20),
        ),
    ]
