# Generated by Django 4.2.7 on 2025-07-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0003_strategycondition_sl_tp_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
