# Generated by Django 4.2.7 on 2025-08-06 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strategy', '0004_strategy_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('trade_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('average_price', models.FloatField(blank=True, null=True)),
                ('ltp', models.FloatField()),
                ('pnl', models.FloatField()),
                ('order_type', models.CharField(choices=[('NRML', 'NRML'), ('MIS', 'MIS')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='strategy.strategy')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
