# Generated by Django 4.2.7 on 2025-08-14 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strategy', '0005_trade'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyPayload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.CharField(max_length=50)),
                ('expiry', models.CharField(max_length=20)),
                ('strike_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('option_type', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('trade_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target_profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('candle_duration', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='strategy.strategy')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
