# Generated by Django 5.1.1 on 2024-09-19 08:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.IntegerField(db_index=True, default='', unique=True)),
                ('otp', models.CharField(blank=True, max_length=10, null=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(db_index=True, default='', max_length=50, unique=True)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('username', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('strategy_id', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('description', models.TextField()),
                ('advantages', models.TextField()),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='algotrade_user_strategy', to='algo_app.user', verbose_name='User-Strategy')),
            ],
        ),
        migrations.CreateModel(
            name='UserOrders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=50)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to='algo_app.user', verbose_name='User-Order')),
            ],
            options={
                'verbose_name': 'UserOrder',
                'verbose_name_plural': 'UserOrders',
            },
        ),
        migrations.CreateModel(
            name='UserStrategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('strategy_id', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('description', models.TextField()),
                ('advantages', models.TextField()),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_strategy', to='algo_app.user', verbose_name='User-Strategy')),
            ],
            options={
                'verbose_name': 'UserStrategy',
                'verbose_name_plural': 'UserStrategys',
            },
        ),
        migrations.CreateModel(
            name='UserTradeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('SELL', 'SELL'), ('BUY', 'BUY')], default=None, max_length=10, null=True)),
                ('cepe', models.CharField(choices=[('SELL', 'SELL'), ('BUY', 'BUY')], default=None, max_length=10, null=True)),
                ('trade_price', models.CharField(default='0', max_length=10, null=True)),
                ('index', models.CharField(default=None, max_length=25, null=True)),
                ('token', models.IntegerField(default=0)),
                ('symbol', models.CharField(default=None, max_length=40, null=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_trades', to='algo_app.user', verbose_name='User-Trades')),
            ],
            options={
                'verbose_name': 'UserTradeDetail',
                'verbose_name_plural': 'UserTradeDetail',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet', to='algo_app.user', verbose_name='User-Wallet')),
            ],
        ),
    ]
