# Generated by Django 4.2.7 on 2025-06-10 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('algo_app', '0002_remove_wallet_amount_wallet_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('symbol', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('expiry_date', models.DateField(db_index=True)),
                ('strike', models.CharField(max_length=255)),
                ('lotsize', models.CharField(max_length=255)),
                ('instrumenttype', models.CharField(max_length=255)),
                ('exch_seg', models.CharField(max_length=255)),
                ('tick_size', models.CharField(max_length=255)),
            ],
        ),
    ]
