# Generated by Django 4.2.7 on 2025-06-17 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('algo_app', '0003_token_remove_wallet_amount_wallet_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('signal', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('trade_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('token', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_details', to='algo_app.token', verbose_name='Trade Details')),
            ],
        ),
    ]
