# Generated by Django 4.2.7 on 2025-06-20 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algo_app', '0004_remove_wallet_amount_wallet_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='phone',
            field=models.CharField(db_index=True, default='', max_length=50, unique=True),
        ),
    ]
