# Generated by Django 4.2.7 on 2025-06-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo_app', '0007_alter_user_name_alter_user_phone_alter_wallet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
