# Generated by Django 4.2.7 on 2025-07-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo_app', '0008_user_verification_code_alter_wallet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='angelonecredential',
            name='api_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
