# Generated by Django 4.2.7 on 2025-08-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo_app', '0009_angelonecredential_api_key_alter_wallet_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradedetails',
            name='token',
        ),
        migrations.AddField(
            model_name='tradedetails',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tradedetails',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tradedetails',
            name='strike_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tradedetails',
            name='symbol',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
